# Generated by Django 5.2.8 on 2026-02-18 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255)),
                ('track_id', models.CharField(max_length=255)),
                ('name_track', models.CharField(max_length=512)),
                ('artist_name', models.CharField(max_length=255)),
                ('audio_url', models.URLField()),
                ('album_image', models.URLField()),
            ],
            options={
                'verbose_name': 'Избранный трек',
                'verbose_name_plural': 'Избранные треки',
            },
        ),
    ]
