# Generated by Django 5.2.8 on 2026-02-19 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favoritetrack',
            unique_together={('user_id', 'track_id')},
        ),
    ]
